name: C Build & Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt update && sudo apt install build-essential -y

    - name: Compile C code
      run: gcc *.c -o app

    - name: Run compiled app
      run: echo "Sample input" | ./app
